strong refactor

diff --git a/podeen_base b/podeen_base
--- a/podeen_base
+++ b/podeen_base
@@ -12,36 +12,51 @@
 ### Functions
 #############
 
+try_run () {
+    if "$@" >/dev/null 2>&1; then
+        printf "\n"
+    else
+        printf ": %s\n" "command failed"
+    fi
+}
+# ---
 sudo_privilege () {
     id -Gn 2>/dev/null | grep -qw "sudo"
 }
 # ---
 testing_setup() {
     [ -s /etc/apt/sources.list ] && grep '^[^#]' /etc/apt/sources.list >/dev/null || return
-    repo="deb http://deb.debian.org/debian testing main contrib"
+    REPO="deb http://deb.debian.org/debian testing main contrib"
     if ! grep -E "^deb[[:space:]]*http://deb.debian.org/debian[[:space:]]*(testing|unstable)" /etc/apt/sources.list >/dev/null 2>&1; then
-        { echo "$repo" | sudo tee -a /etc/apt/sources.list >/dev/null; } && sudo cp "${SCRIPTPATH}/base/preferences" "/etc/apt/" >/dev/null 2>&1
+        { echo "$REPO" | sudo tee -a /etc/apt/sources.list >/dev/null; } && sudo cp "$SCRIPTPATH/base/preferences" "/etc/apt/" >/dev/null 2>&1
     fi
 }
 # ---
 store_conf () {
     backup_conf () {
         if [ -f "$1" ]; then
+            printf "%s" "removing '$1'"
             if [ -L "$1" ]; then
-                unlink "$1"
+                try_run unlink "$1"
             else
-                mv "$1" "${RESTORE}/"
+                try_run mv "$1" "$RESTORE/"
             fi
         fi
     }
-    RESTORE="${HOME}/.podeen_recovery"
+    # ---
+    RESTORE="$HOME/.podeen_recovery"
     mkdir -p "$RESTORE"
-    backup_conf "${HOME}/.profile"
-    backup_conf "${HOME}/.bashrc"
-    backup_conf "${HOME}/.bash_logout"
-    backup_conf "${HOME}/.vimrc"
-    backup_conf "${HOME}/.tmux.conf"
-    backup_conf "${HOME}/.local/bin/fetch.sh"
+    printf "\n%s\n" "REMOVING BASE SCRIPTS"
+    for SCRIPT in \
+        ".profile" \
+        ".bashrc" \
+        ".bash_logout" \
+        ".vimrc" \
+        ".tmux.conf" \
+        ".local/bin/fetch.sh"
+    do
+        backup_conf "$HOME/$SCRIPT"
+    done
 }
 
 
@@ -59,7 +74,7 @@ if [ "$(id -u)" -eq 0 ]; then
     exit 1
 fi
 # ---
-if [ -d "${HOME}/.podeen_recovery" ]; then
+if [ -d "$HOME/.podeen_recovery" ]; then
     printf "\n%s"   "════════════════ Warning: podeen already set ════════════════"
     printf "\n%s\n" "Remove ~/.podeen_recovery directory and run this script again"
     exit 1
@@ -111,12 +126,26 @@ fi
 #########
 
 store_conf
-cp "${SCRIPTPATH}/base/.profile" "${HOME}/"
-cp "${SCRIPTPATH}/base/.bashrc" "${HOME}/"
-cp "${SCRIPTPATH}/base/.bash_logout" "${HOME}/"
-cp "${SCRIPTPATH}/base/.vimrc" "${HOME}/"
-cp "${SCRIPTPATH}/base/.tmux.conf" "${HOME}/"
-mkdir -p "${HOME}/.local/bin/" && cp "${SCRIPTPATH}/base/fetch.sh" "${HOME}/.local/bin/"
+printf "\n%s\n" "COPYING BASE SCRIPTS"
+for SCRIPT in \
+    ".profile" \
+    ".bashrc" \
+    ".bash_logout" \
+    ".vimrc" \
+    ".tmux.conf" \
+    "fetch.sh"
+do
+    printf "%s" "copying '$SCRIPT'"
+    case $SCRIPT in
+        "fetch.sh")
+            mkdir -p "$HOME/.local/bin/" >/dev/null 2>&1 || continue
+            try_run cp "$SCRIPTPATH/base/$SCRIPT" "$HOME/.local/bin/"
+            ;;
+        *)
+            try_run cp "$SCRIPTPATH/base/$SCRIPT" "$HOME/"
+            ;;
+    esac
+done
 # ---
 if sudo_privilege; then
     sudo chsh -s "$(command -v bash)" "$USER"
diff --git a/podeen_code b/podeen_code
--- a/podeen_code
+++ b/podeen_code
@@ -12,6 +12,14 @@
 ### Functions
 #############
 
+try_run () {
+    if "$@" >/dev/null 2>&1; then
+        printf "\n"
+    else
+        printf ": %s\n" "command failed"
+    fi
+}
+# ---
 sudo_privilege () {
     id -Gn 2>/dev/null | grep -qw "sudo"
 }
@@ -77,12 +85,12 @@ fi
 printf "\n%s\n" "UNINSTALLING ALL EXTENSIONS"
 for EXTENSION in $(\code --list-extensions); do
     printf "%s" "uninstalling '$EXTENSION'"
-    \code --uninstall-extension "$EXTENSION" >/dev/null 2>&1 && printf "\n" || printf ": %s\n" "uninstall failed"
+    try_run \code --uninstall-extension "$EXTENSION"
 done
-rm -rf "${HOME}/.config/Code/CachedExtensionVSIXs" \
-       "${HOME}/.vscode/extensions" 2>/dev/null || true
+rm -rf "$HOME/.config/Code/CachedExtensionVSIXs" \
+       "$HOME/.vscode/extensions" 2>/dev/null || true
 # ---
-printf "\n%s\n" "INSTALLING BASE EXTENSIONS"
+printf "\n%s\n" "INSTALLING CODE EXTENSIONS"
 for EXTENSION in \
     github.copilot \
     james-yu.latex-workshop \
@@ -91,13 +99,13 @@ for EXTENSION in \
     ms-toolsai.jupyter
 do
     printf "%s" "installing '$EXTENSION'"
-    \code --install-extension "$EXTENSION" >/dev/null 2>&1 && printf "\n" || printf ": %s\n" "install failed"
+    try_run \code --install-extension "$EXTENSION"
 done
 # ---
-BASE="${HOME}/.config/Code/User"
+BASE="$HOME/.config/Code/User"
 if mkdir -p "$BASE"; then
-    cat "${SCRIPTPATH}/code/settings.json" > "${BASE}/settings.json"
-    cat "${SCRIPTPATH}/code/keybindings.json" > "${BASE}/keybindings.json"
+    cat "$SCRIPTPATH/code/settings.json" > "$BASE/settings.json"
+    cat "$SCRIPTPATH/code/keybindings.json" > "$BASE/keybindings.json"
 fi
 
 
diff --git a/podeen_plug b/podeen_plug
--- a/podeen_plug
+++ b/podeen_plug
@@ -83,13 +83,13 @@ set -- \
     "https://github.com/cohama/lexima.vim.git" \
     "https://github.com/wellle/context.vim.git"
 # ---
-VIM=${HOME}/.vim
-START="${VIM}/pack/plug/start"
+VIM=$HOME/.vim
+START="$VIM/pack/plug/start"
 FOUND=""
 # ---
-mkdir -p "$START" || exit 1
-if [ ! -d "${VIM}/plugin" ] && [ -d "${SCRIPTPATH}/plug" ]; then
-    cp -R "${SCRIPTPATH}/plug" "${VIM}/plugin"
+mkdir -p "$START" >/dev/null 2>&1 || { printf "\n%s\n" "'$START' failed makedir"; exit 1; }
+if [ ! -d "$VIM/plugin" ] && [ -d "$SCRIPTPATH/plug" ]; then
+    cp -R "$SCRIPTPATH/plug" "$VIM/plugin" >/dev/null 2>&1 || printf "%s\n" "'$VIM/plugin' failed copy"
 fi
 # ---
 for DIR in "$START"/*; do
