new look and non-sudo install

diff --git a/podeen_plug b/podeen_plug
--- a/podeen_plug
+++ b/podeen_plug
@@ -10,36 +10,58 @@
 
 
 
-### Check & Funcs
-#################
+### Functions
+#############
 
-version_check () {
-    if ! command -v vim >/dev/null 2>&1 || ! command vim --version | grep -q 'Vi IMproved 9'; then
-        printf "\n%s"   "═══════ Warning: Vim9 not found ══════"
-        printf "\n%s\n" "Install Vim9 and run this script again"
-        exit 1
-    fi
-}
-# ---
-warning_message () {
-    if [ "$(id -u)" = 0 ]; then
-        printf "\n%s"   "This script MUST NOT be run as root user since it makes changes"
-        printf "\n%s"   "to the \$HOME directory of the \$USER executing this script."
-        printf "\n%s"   "The \$HOME directory of the root user is, of course, '/root'."
-        printf "\n%s"   "We don't want to mess around in there. So run this script as a"
-        printf "\n%s\n" "normal user. You will be asked for a sudo password when necessary."
-        exit 1
-    fi
+sudo_privilege () {
+    sudo -n -l 2>/dev/null | grep -q "(ALL) ALL"
+    return $((! $?))
 }
 # ---
 reset_plugin() {
     printf "\n%s\n" "$OPERATION"
     if [ -d "$PLUGIN" ]; then
-        command git -C "$PLUGIN" pull
+        \git -C "$PLUGIN" pull
     else
-        command git clone "$REPOSITORY" "$PLUGIN"
+        \git clone "$REPOSITORY" "$PLUGIN"
     fi
 }
+
+
+
+
+### Checks
+##########
+
+if [ "$(id -u)" -eq 0 ]; then
+    printf "\n%s"   "This script MUST NOT be run as root user since it makes changes"
+    printf "\n%s"   "to the \$HOME directory of the \$USER executing this script."
+    printf "\n%s"   "The \$HOME directory of the root user is, of course, '/root'."
+    printf "\n%s"   "We don't want to mess around in there. So run this script as a"
+    printf "\n%s\n" "normal user. You will be asked for a sudo password when necessary."
+    exit 1
+fi
+# ---
+if ! command -v vim >/dev/null 2>&1 || ! \vim --version | grep -q 'Vi IMproved 9'; then
+    printf "\n%s"   "═══════ Warning: Vim9 not found ══════"
+    printf "\n%s\n" "Install Vim9 and run this script again"
+    exit 1
+fi
+
+
+
+
+### Podeen-Plug
+###############
+
+cat << EOF
+.   .   ___         _                ___ _
+|\\_/|  | _ \\___  __| |___ ___ _ _   | _ \\ |_  _ __ _
+(O.o)  |  _/ _ \\/ _\` / -_) -_) ' \\  |  _/ | || / _\` |
+(> <)  |_| \\___/\\__,_\\___\\___|_||_| |_| |_|\\_,_\\__, |
+                                               |___/
+
+EOF
 
 
 
@@ -47,13 +69,13 @@ reset_plugin() {
 ### Path & Dependencies
 #######################
 
-version_check
-warning_message
-SCRIPTPATH="$( cd "$(command dirname "$0")" ; pwd -P )" || exit 1
-[ -f "${SCRIPTPATH}/podeen.txt" ] && cat "${SCRIPTPATH}/podeen.txt"
-command sudo apt-get update
-command sudo apt-get upgrade -qq -y
-command sudo apt-get install -qq -y git nodejs
+SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )" || exit 1
+if sudo_privilege; then
+    sudo sh -c '
+        apt-get update && apt-get upgrade -qq -y &&
+        apt-get install -qq -y git nodejs
+    '
+fi
 
 
 
@@ -63,7 +85,7 @@ command sudo apt-get install -qq -y git nodejs
 
 VIM=${HOME}/.vim
 START="${VIM}/pack/plug/start"
-command mkdir -p "$START"
+mkdir -p "$START"
 [ -d "${VIM}/plugin" ] || cp -r "${SCRIPTPATH}/plug" "${VIM}/plugin"
 # ---
 OPERATION="RESETTING CTRLP"
