make installers POSIX compliant

diff --git a/podeen-base b/podeen-base
--- a/podeen-base
+++ b/podeen-base
@@ -1,4 +1,4 @@
-#!/usr/bin/env bash
+#!/usr/bin/env sh
 
 # This base setup script will install a minimal work environment,
 # complete with all the bells and whistles needed to start working properly.
@@ -16,48 +16,46 @@
 ### Check & Funcs
 #################
 
-RED='\033[1;36m'
-NC='\033[0m'
-# ---
-if [[ -d "${HOME}/.podeen-recovery" ]]; then
-    printf "\n${RED}%s${NC}"   "════════════════ Warning: podeen already set ════════════════"
-    printf "\n${RED}%s${NC}\n" "Remove ~/.podeen-recovery directory and run this script again"
+if [ -d "${HOME}/.podeen-recovery" ]; then
+    printf "\n%s"   "════════════════ Warning: podeen already set ════════════════"
+    printf "\n%s\n" "Remove ~/.podeen-recovery directory and run this script again"
     exit 1
 fi
 # ---
-function warning-message () {
-    if [[ "$(id -u)" = 0 ]]; then
-        printf "\n${RED}%s${NC}"     "This script MUST NOT be run as root user since it makes changes"
-        printf "\n${RED}%s${NC}"     "to the \$HOME directory of the \$USER executing this script."
-        printf "\n${RED}%s${NC}"     "The \$HOME directory of the root user is, of course, '/root'."
-        printf "\n${RED}%s${NC}"     "We don't want to mess around in there. So run this script as a"
-        printf "\n${RED}%s${NC}\n" "normal user. You will be asked for a sudo password when necessary."
+warning_message () {
+    if [ "$(id -u)" = 0 ]; then
+        printf "\n%s"   "This script MUST NOT be run as root user since it makes changes"
+        printf "\n%s"   "to the \$HOME directory of the \$USER executing this script."
+        printf "\n%s"   "The \$HOME directory of the root user is, of course, '/root'."
+        printf "\n%s"   "We don't want to mess around in there. So run this script as a"
+        printf "\n%s\n" "normal user. You will be asked for a sudo password when necessary."
         exit 1
     fi
 }
 # ---
-function error-echo () {
-    printf "${RED}ERROR: %s${NC}\n" "$1" >&2
+error_echo () {
+    printf "ERROR: %s\n" "$1" >&2
     exit 1
 }
 # ---
-function store-conf () {
-    function backup-conf () {
-        if [[ -f "$1" ]]; then
-            if [[ -L "$1" ]]; then
+store_conf () {
+    backup_conf () {
+        if [ -f "$1" ]; then
+            if [ -L "$1" ]; then
                 command unlink "$1"
             else
                 mv "$1" "${RESTORE}/"
             fi
         fi
     }
-    RESTORE="${HOME}/.podeen-recovery" && command mkdir -p "${RESTORE}"
-    backup-conf "${HOME}/.bash_logout"
-    backup-conf "${HOME}/.bashrc"
-    backup-conf "${HOME}/.profile"
-    backup-conf "${HOME}/.tmux.conf"
-    backup-conf "${HOME}/.vimrc"
-    backup-conf "${HOME}/.local/bin/fetch.sh"
+    RESTORE="${HOME}/.podeen-recovery"
+    command mkdir -p "$RESTORE"
+    backup_conf "${HOME}/.bash_logout"
+    backup_conf "${HOME}/.bashrc"
+    backup_conf "${HOME}/.profile"
+    backup_conf "${HOME}/.tmux.conf"
+    backup_conf "${HOME}/.vimrc"
+    backup_conf "${HOME}/.local/bin/fetch.sh"
 }
 
 
@@ -66,12 +64,12 @@ function store-conf () {
 ### Path & Dependencies
 #######################
 
-warning-message
+warning_message
 SCRIPTPATH="$( cd "$(command dirname "$0")" ; pwd -P )" || exit 1
-"${SCRIPTPATH}/base/fetch.sh"
-command sudo apt-get update && sudo apt-get upgrade -qq -y || error-echo "syncing repos"
+command sudo apt-get update || error_echo "update repos"
+command sudo apt-get upgrade -qq -y || error_echo "upgrade repos"
 command sudo apt-get install -qq -y bash bash-completion fzy file fd-find xclip trash-cli \
-      git tmux vim python3 wamerican htop || error-echo "installing from apt"
+      git tmux vim python3 wamerican htop || error_echo "installing packages"
 
 
 
@@ -79,7 +77,7 @@ command sudo apt-get install -qq -y bash bash-completion fzy file fd-find xclip 
 ### Start
 #########
 
-store-conf
+store_conf
 cp "${SCRIPTPATH}/base/.bash_logout" "${HOME}/"
 cp "${SCRIPTPATH}/base/.bashrc" "${HOME}/"
 cp "${SCRIPTPATH}/base/.profile" "${HOME}/"
@@ -95,4 +93,4 @@ cp "${SCRIPTPATH}/base/fetch.sh" "${HOME}/.local/bin/"
 ### Finish
 ##########
 
-printf "\n${RED}%s${NC}\n" "setup complete"
+printf "\n%s\n" "setup complete"
diff --git a/podeen-code b/podeen-code
--- a/podeen-code
+++ b/podeen-code
@@ -1,4 +1,4 @@
-#!/usr/bin/env bash
+#!/usr/bin/env sh
 
 # VSCode reset with just few tweaks and GitHub-Copilot extension:
 # https://marketplace.visualstudio.com/items?itemName=GitHub.copilot
@@ -12,28 +12,25 @@
 ### Check & Funcs
 #################
 
-RED='\033[1;36m'
-NC='\033[0m'
-# ---
-if [[ ! -x "$(command -v "code")" ]]; then
-    printf "\n${RED}%s${NC}"   "═══════ Warning: VSCode not found ══════"
-    printf "\n${RED}%s${NC}\n" "Install VSCode and run this script again"
+if ! command -v code >/dev/null 2>&1; then
+    printf "\n%s"   "═══════ Warning: VSCode not found ══════"
+    printf "\n%s\n" "Install VSCode and run this script again"
     exit 1
 fi
 # ---
-function warning-message () {
-    if [[ "$(id -u)" = 0 ]]; then
-        printf "\n${RED}%s${NC}"     "This script MUST NOT be run as root user since it makes changes"
-        printf "\n${RED}%s${NC}"     "to the \$HOME directory of the \$USER executing this script."
-        printf "\n${RED}%s${NC}"     "The \$HOME directory of the root user is, of course, '/root'."
-        printf "\n${RED}%s${NC}"     "We don't want to mess around in there. So run this script as a"
-        printf "\n${RED}%s${NC}\n" "normal user. You will be asked for a sudo password when necessary."
+warning_message () {
+    if [ "$(id -u)" = 0 ]; then
+        printf "\n%s"   "This script MUST NOT be run as root user since it makes changes"
+        printf "\n%s"   "to the \$HOME directory of the \$USER executing this script."
+        printf "\n%s"   "The \$HOME directory of the root user is, of course, '/root'."
+        printf "\n%s"   "We don't want to mess around in there. So run this script as a"
+        printf "\n%s\n" "normal user. You will be asked for a sudo password when necessary."
         exit 1
     fi
 }
 # ---
-function error-echo () {
-    printf "${RED}ERROR: %s${NC}\n" "$1" >&2
+error_echo () {
+    printf "ERROR: %s\n" "$1" >&2
     exit 1
 }
 
@@ -43,11 +40,12 @@ function error-echo () {
 ### Path & Dependencies
 #######################
 
-warning-message
+warning_message
 SCRIPTPATH="$( cd "$(command dirname "$0")" ; pwd -P )" || exit 1
-"${SCRIPTPATH}/base/fetch.sh"
-command sudo apt-get update && sudo apt-get upgrade -qq -y || error-echo "syncing repos"
-command sudo apt-get install -qq -y bash dash git gnome-keyring fonts-jetbrains-mono || error-echo "installing from apt"
+command sudo apt-get update || error_echo "update repos"
+command sudo apt-get upgrade -qq -y || error_echo "upgrade repos"
+command sudo apt-get install -qq -y dash bash git fonts-jetbrains-mono \
+      gnome-keyring || error_echo "installing packages"
 
 
 
@@ -55,24 +53,13 @@ command sudo apt-get install -qq -y bash dash git gnome-keyring fonts-jetbrains-
 ### Start
 #########
 
-BASE="${HOME}/.config/Code/User" && command mkdir -p "${BASE}"
+BASE="${HOME}/.config/Code/User"
+command mkdir -p "$BASE"
 for EXTENSION in $(command code --list-extensions); do
-    command code --uninstall-extension "${EXTENSION}" &>/dev/null
+    command code --uninstall-extension "$EXTENSION" >/dev/null 2>&1
 done
 # ---
-while read -p "$(echo -e "\n${RED}Would you like to install copilot extension? (yes/no): ${NC}")" COPILOT; do
-    case "$COPILOT" in
-        [Yy] | [Yy][Ee][Ss])
-            command code --install-extension github.copilot
-            break;;
-        [Nn] | [Nn][Oo])
-            echo "Skipping copilot extension installation"
-            break;;
-        *)
-            echo "Invalid input. Answer with 'yes' or 'no'";;
-    esac
-done
-# ---
+command code --install-extension github.copilot || error_echo "installing extansions"
 cat "${SCRIPTPATH}/code/settings.json" > "${BASE}/settings.json"
 cat "${SCRIPTPATH}/code/keybindings.json" > "${BASE}/keybindings.json"
 
@@ -82,4 +69,4 @@ cat "${SCRIPTPATH}/code/keybindings.json" > "${BASE}/keybindings.json"
 ### Finish
 ##########
 
-printf "\n${RED}%s${NC}\n" "setup complete"
+printf "\n%s\n" "setup complete"
diff --git a/podeen-plug b/podeen-plug
--- a/podeen-plug
+++ b/podeen-plug
@@ -1,4 +1,4 @@
-#!/usr/bin/env bash
+#!/usr/bin/env sh
 
 # Ctrlp*     -> https://github.com/ctrlpvim/ctrlp.vim
 # Sandwich*  -> https://github.com/machakann/vim-sandwich
@@ -12,37 +12,34 @@
 ### Check & Funcs
 #################
 
-RED='\033[1;36m'
-NC='\033[0m'
-# ---
-if [[ ! -x "$(command -v "vim")" || ! "$(command vim --version | grep -oE 'Vi IMproved 9')" == "Vi IMproved 9" ]]; then
-    printf "\n${RED}%s${NC}"   "═══════ Warning: Vim9 not found ══════"
-    printf "\n${RED}%s${NC}\n" "Install Vim9 and run this script again"
+if ! command -v vim >/dev/null 2>&1 || ! command vim --version | grep -q 'Vi IMproved 9'; then
+    printf "\n%s"   "═══════ Warning: Vim9 not found ══════"
+    printf "\n%s\n" "Install Vim9 and run this script again"
     exit 1
 fi
 # ---
-function warning-message () {
-    if [[ "$(id -u)" = 0 ]]; then
-        printf "\n${RED}%s${NC}"     "This script MUST NOT be run as root user since it makes changes"
-        printf "\n${RED}%s${NC}"     "to the \$HOME directory of the \$USER executing this script."
-        printf "\n${RED}%s${NC}"     "The \$HOME directory of the root user is, of course, '/root'."
-        printf "\n${RED}%s${NC}"     "We don't want to mess around in there. So run this script as a"
-        printf "\n${RED}%s${NC}\n" "normal user. You will be asked for a sudo password when necessary."
+warning_message () {
+    if [ "$(id -u)" = 0 ]; then
+        printf "\n%s"   "This script MUST NOT be run as root user since it makes changes"
+        printf "\n%s"   "to the \$HOME directory of the \$USER executing this script."
+        printf "\n%s"   "The \$HOME directory of the root user is, of course, '/root'."
+        printf "\n%s"   "We don't want to mess around in there. So run this script as a"
+        printf "\n%s\n" "normal user. You will be asked for a sudo password when necessary."
         exit 1
     fi
 }
 # ---
-function error-echo () {
-    printf "${RED}ERROR: %s${NC}\n" "$1" >&2
+error_echo () {
+    printf "ERROR: %s\n" "$1" >&2
     exit 1
 }
 # ---
-function reset-plugin () {
-    printf "\n${RED}%s${NC}\n" "${OPERATION}"
-    if [[ -d "${PLUGIN}" ]]; then
-        command git -C "${PLUGIN}" pull
+reset_plugin() {
+    printf "\n%s\n" "$OPERATION"
+    if [ -d "$PLUGIN" ]; then
+        command git -C "$PLUGIN" pull
     else
-        command git clone "${REPOSITORY}" "${PLUGIN}"
+        command git clone "$REPOSITORY" "$PLUGIN"
     fi
 }
 
@@ -52,10 +49,11 @@ function reset-plugin () {
 ### Path & Dependencies
 #######################
 
-warning-message
+warning_message
 SCRIPTPATH="$( cd "$(command dirname "$0")" ; pwd -P )" || exit 1
-"${SCRIPTPATH}/base/fetch.sh"
-command sudo apt-get install -qq -y git exuberant-ctags || error-echo "installing from apt"
+command sudo apt-get update || error_echo "update repos"
+command sudo apt-get upgrade -qq -y || error_echo "upgrade repos"
+command sudo apt-get install -qq -y git exuberant-ctags || error_echo "installing packages"
 
 
 
@@ -63,34 +61,36 @@ command sudo apt-get install -qq -y git exuberant-ctags || error-echo "installin
 ### Start
 #########
 
-VIM=${HOME}/.vim && command mkdir -p "${VIM}"
-START="${VIM}/pack/plug/start" && command mkdir -p "${START}"
-[[ -d "${VIM}/plugin" ]] || cp -r "${SCRIPTPATH}/plug" "${VIM}/plugin"
+VIM=${HOME}/.vim
+START="${VIM}/pack/plug/start"
+command mkdir -p "$VIM"
+command mkdir -p "$START"
+[ -d "${VIM}/plugin" ] || cp -r "${SCRIPTPATH}/plug" "${VIM}/plugin"
 # ---
 OPERATION="RESETTING CTRLP"
 REPOSITORY="https://github.com/ctrlpvim/ctrlp.vim.git"
 PLUGIN="${START}/ctrlp"
-reset-plugin
+reset_plugin
 # ---
 OPERATION="RESETTING SANDWICH"
 REPOSITORY="https://github.com/machakann/vim-sandwich.git"
 PLUGIN="${START}/sandwich"
-reset-plugin
+reset_plugin
 # ---
 OPERATION="RESETTING COMMENTARY"
 REPOSITORY="https://github.com/tpope/vim-commentary.git"
 PLUGIN="${START}/commentary"
-reset-plugin
+reset_plugin
 # ---
 OPERATION="RESETTING LEXIMA"
 REPOSITORY="https://github.com/cohama/lexima.vim.git"
 PLUGIN="${START}/lexima"
-reset-plugin
+reset_plugin
 # ---
 OPERATION="RESETTING CONTEXT"
 REPOSITORY="https://github.com/wellle/context.vim.git"
 PLUGIN="${START}/context"
-reset-plugin
+reset_plugin
 
 
 
@@ -98,4 +98,4 @@ reset-plugin
 ### Finish
 ##########
 
-printf "\n${RED}%s${NC}\n" "setup complete"
+printf "\n%s\n" "setup complete"
