better sudo handling

diff --git a/podeen_base b/podeen_base
--- a/podeen_base
+++ b/podeen_base
@@ -104,8 +104,8 @@ EOF
 
 
 
-### Packages & Sudo
-###################
+### Packages
+############
 
 PACKAGES="git bash bash-completion fzy file fd-find xclip trash-cli procps \
 x11-xkb-utils less tmux vim exuberant-ctags wamerican make gcc gdb valgrind"
@@ -126,34 +126,36 @@ fi
 
 
 
-### Path & Dependencies
-#######################
+### Dependencies
+################
 
 SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )" || exit 1
-while IFS='' read -r OSRELEASELINE; do
-    case "$OSRELEASELINE" in
-        ID=debian | VERSION_ID=\"13\" | "VERSION=\"13 (trixie)\"") LINECOUNT=$(( ${LINECOUNT:-0} + 1 ));;
-        *) :;;
-    esac
-    if [ "${LINECOUNT:-0}" -eq 3 ]; then
-        testing_setup
-        break
-    fi
-done < /etc/os-release 2>/dev/null
-# ---
-sudo sh -c '
-    apt-get update &&
-    apt-get upgrade -qq -y --allow-downgrades &&
-    apt-get purge -qq -y vim-tiny vim-gtk3 || true
-    for PKG in "$@"; do
-        apt-get install -y -qq --no-install-recommends "$PKG" || true
-    done
-    apt-get -qq -y autoremove --purge &&
-    apt-get -qq -y autoclean
-' _ $PACKAGES || {
-    printf "\n%s\n" "packages installation failed"
-    exit 1
-}
+if sudo_privileges; then
+    while IFS='' read -r OSRELEASELINE; do
+        case "$OSRELEASELINE" in
+            ID=debian | VERSION_ID=\"13\" | "VERSION=\"13 (trixie)\"") LINECOUNT=$(( ${LINECOUNT:-0} + 1 ));;
+            *) :;;
+        esac
+        if [ "${LINECOUNT:-0}" -eq 3 ]; then
+            testing_setup
+            break
+        fi
+    done < /etc/os-release 2>/dev/null
+    # ---
+    sudo sh -c '
+        apt-get update &&
+        apt-get upgrade -qq -y --allow-downgrades &&
+        apt-get purge -qq -y vim-tiny vim-gtk3 || true
+        for PKG in "$@"; do
+            apt-get install -y -qq --no-install-recommends "$PKG" || true
+        done
+        apt-get -qq -y autoremove --purge &&
+        apt-get -qq -y autoclean
+    ' _ $PACKAGES || {
+        printf "\n%s\n" "packages installation failed"
+        exit 1
+    }
+fi
 
 
 
diff --git a/podeen_code b/podeen_code
--- a/podeen_code
+++ b/podeen_code
@@ -94,19 +94,20 @@ fi
 ### Path & Dependencies
 #######################
 
-SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )" || exit 1
-sudo sh -c '
-    apt-get update &&
-    apt-get upgrade -qq -y --allow-downgrades &&
-    for PKG in "$@"; do
-        apt-get install -y -qq --no-install-recommends "$PKG" || true
-    done
-    apt-get -qq -y autoremove --purge &&
-    apt-get -qq -y autoclean
-' _ $PACKAGES || {
-    printf "\n%s\n" "packages installation failed"
-    exit 1
-}
+if sudo_privileges; then
+    sudo sh -c '
+        apt-get update &&
+        apt-get upgrade -qq -y --allow-downgrades &&
+        for PKG in "$@"; do
+            apt-get install -y -qq --no-install-recommends "$PKG" || true
+        done
+        apt-get -qq -y autoremove --purge &&
+        apt-get -qq -y autoclean
+    ' _ $PACKAGES || {
+        printf "\n%s\n" "packages installation failed"
+        exit 1
+    }
+fi
 
 
 
@@ -135,6 +136,7 @@ do
 done
 # ---
 BASE="$HOME/.config/Code/User"
+SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )" || exit 1
 if mkdir -p "$BASE"; then
     cat "$SCRIPTPATH/code/settings.json" > "$BASE/settings.json"
     cat "$SCRIPTPATH/code/keybindings.json" > "$BASE/keybindings.json"
diff --git a/podeen_plug b/podeen_plug
--- a/podeen_plug
+++ b/podeen_plug
@@ -62,11 +62,12 @@ EOF
 
 
 
-### Packages & Sudo
-###################
+### Packages
+############
 
-PACKAGES="git vim-gtk3 python3-full python3-pip black fonts-cascadia-code"
-for PKG in $PACKAGES; do
+PACKAGES="git python3-full python3-pip black"
+EXTRAPKG="vim-gtk3 fonts-cascadia-code"
+for PKG in $PACKAGES $EXTRAPKG; do
     if ! apt-get -s install "$PKG" >/dev/null 2>&1; then
         PROBLEMS="${PROBLEMS:+$PROBLEMS }$PKG"
     fi
@@ -83,23 +84,46 @@ fi
 
 
 
-### Path & Dependencies
-#######################
+### Dependencies
+################
 
-SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )" || exit 1
-sudo sh -c '
-    apt-get update &&
-    apt-get upgrade -qq -y --allow-downgrades &&
-    apt-get purge -qq -y vim-tiny vim || true
-    for PKG in "$@"; do
-        apt-get install -y -qq --no-install-recommends "$PKG" || true
-    done
-    apt-get -qq -y autoremove --purge &&
-    apt-get -qq -y autoclean
-' _ $PACKAGES || {
-    printf "\n%s\n" "packages installation failed"
-    exit 1
-}
+if sudo_privileges; then
+    sudo sh -c '
+        apt-get update &&
+        apt-get upgrade -qq -y --allow-downgrades &&
+        apt-get purge -qq -y vim-tiny vim || true
+        for PKG in "$@"; do
+            apt-get install -y -qq --no-install-recommends "$PKG" || true
+        done
+    ' _ $PACKAGES || {
+        printf "\n%s\n" "packages installation failed"
+        exit 1
+    }
+    # ---
+    sudo sh -c '
+        printf "\n%s" "extra packages:"
+        for PKG in "$@"; do
+            printf "%s" " $PKG"
+        done
+        printf "\n"
+        read -r -p "wish to proceed installing them too? [y/N] " ANS
+        case "$ANS" in
+            y | Y | yes | YES)
+                for PKG in "$@"; do
+                    apt-get install -y -qq --no-install-recommends "$PKG" || true
+                done
+                ;;
+            *)
+                { :; }
+                ;;
+        esac
+        apt-get -qq -y autoremove --purge &&
+        apt-get -qq -y autoclean
+    ' _ $EXTRAPKG || {
+        printf "\n%s\n" "packages installation failed"
+        exit 1
+    }
+fi
 
 
 
@@ -148,6 +172,7 @@ for URL in "$@"; do
     esac
 done
 # ---
+SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )" || exit 1
 if [ ! -d "$VIM/plugin" ] && [ -d "$SCRIPTPATH/plug" ]; then
     cp -R "$SCRIPTPATH/plug" "$VIM/plugin"
 fi
