massive refactor

diff --git a/podeen_base b/podeen_base
--- a/podeen_base
+++ b/podeen_base
@@ -9,11 +9,20 @@
 ### Functions
 #############
 
-sudo_privilege () {
+sudo_privileges () {
     id -Gn 2>/dev/null | grep -qw "sudo"
 }
 # ---
-testing_setup() {
+ask_user () {
+    printf "%s\n" "$1"
+    read -r -p "wish to proceed anyway? [y/N] " ANS
+    case "$ANS" in
+        y | Y | yes | YES) printf "\n%s\n" "setup resumed" ;;
+        *) printf "\n%s\n" "setup interrupted"; exit 1 ;;
+    esac
+}
+# ---
+testing_setup () {
     [ -s /etc/apt/sources.list ] && grep '^[^#]' /etc/apt/sources.list >/dev/null || return
     REPO="deb http://deb.debian.org/debian testing main contrib"
     if ! grep -E "^deb[[:space:]]*http://deb.debian.org/debian[[:space:]]*(testing|unstable)" /etc/apt/sources.list >/dev/null 2>&1; then
@@ -45,12 +54,12 @@ store_conf () {
     mkdir -p "$RESTORE"
     printf "\n%s\n" "REMOVING BASE SCRIPTS"
     for SCRIPT in \
-        ".profile" \
-        ".bashrc" \
-        ".bash_logout" \
-        ".vimrc" \
-        ".tmux.conf" \
-        ".local/bin/fetch.sh"
+        .profile \
+        .bashrc \
+        .bash_logout \
+        .vimrc \
+        .tmux.conf \
+        .local/bin/fetch.sh
     do
         backup_conf "$HOME/$SCRIPT"
     done
@@ -72,8 +81,8 @@ if [ "$(id -u)" -eq 0 ]; then
 fi
 # ---
 if [ -d "$HOME/.podeen_recovery" ]; then
-    printf "\n%s"   "════════════════ Warning: podeen already set ════════════════"
-    printf "\n%s\n" "Remove ~/.podeen_recovery directory and run this script again"
+    printf "\n%s"   "════════════════ WARNING: podeen already set ════════════════"
+    printf "\n%s\n" "remove ~/.podeen_recovery directory and run this script again"
     exit 1
 fi
 
@@ -94,27 +103,60 @@ EOF
 
 
 
+### Packages & Sudo
+###################
+
+PACKAGES="git bash bash-completion fzy file fd-find xclip trash-cli \
+procps less tmux vim exuberant-ctags wamerican make gcc gdb valgrind"
+for PKG in $PACKAGES; do
+    if ! apt-get -s install "$PKG" >/dev/null 2>&1; then
+        PROBLEMS="${PROBLEMS:-} $PKG"
+    fi
+done
+# ---
+if [ -n "$PROBLEMS" ]; then
+    ask_proceed "these packages might cause issues:'$PROBLEMS'"
+fi
+# ---
+if ! sudo_privileges; then
+    ask_proceed "'$USER' does not have sudo privileges"
+fi
+
+
+
+
 ### Path & Dependencies
 #######################
 
 SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )" || exit 1
-if sudo_privilege && command -v apt-get >/dev/null 2>&1; then
-    while IFS='' read -r OSRELEASELINE; do
-        case "$OSRELEASELINE" in
-            ID=debian|ID=\"debian\"|VERSION_ID=13|VERSION_ID=\"13\"|"VERSION_ID=13 (trixie)"|"VERSION_ID=\"13 (trixie)\"") LINECOUNT=$(( ${LINECOUNT:-0} + 1 ));;
-        esac
-        [ "${LINECOUNT:-0}" -eq 2 ] && { testing_setup; break; }
-    done < /etc/os-release 2>/dev/null
-    # ---
-    sudo sh -c '
-        apt-get update &&
-        apt-get upgrade -qq -y --allow-downgrades &&
-        apt-get purge -qq -y vim-tiny vim-gtk3 || true &&
-        apt-get install -qq -y git bash bash-completion fzy file fd-find xclip trash-cli procps less tmux vim exuberant-ctags wamerican make gcc gdb valgrind &&
-        apt-get -qq -y autoremove --purge &&
-        apt-get -qq -y autoclean
-    ' || { printf "\n%s\n" "Package installation failed"; exit 1; }
-fi
+while IFS='' read -r OSRELEASELINE; do
+    case "$OSRELEASELINE" in
+        ID=debian \
+        | ID=\"debian\" \
+        | VERSION_ID=13 \
+        | VERSION_ID=\"13\" \
+        | "VERSION_ID=13 (trixie)" \
+        | "VERSION_ID=\"13 (trixie)\"")
+            LINECOUNT=$(( ${LINECOUNT:-0} + 1 ))
+            ;;
+    esac
+    if [ "${LINECOUNT:-0}" -eq 2 ]; then
+        testing_setup
+        break
+    fi
+done < /etc/os-release 2>/dev/null
+# ---
+sudo sh -c '
+    apt-get update &&
+    apt-get upgrade -qq -y --allow-downgrades &&
+    apt-get purge -qq -y vim-tiny vim-gtk3 || true &&
+    apt-get install -qq -y '"$PACKAGES"' || true &&
+    apt-get -qq -y autoremove --purge &&
+    apt-get -qq -y autoclean
+' || {
+    printf "\n%s\n" "packages installation failed"
+    exit 1
+}
 
 
 
@@ -125,16 +167,16 @@ fi
 store_conf
 printf "\n%s\n" "COPYING BASE SCRIPTS"
 for SCRIPT in \
-    ".profile" \
-    ".bashrc" \
-    ".bash_logout" \
-    ".vimrc" \
-    ".tmux.conf" \
-    "fetch.sh"
+    .profile \
+    .bashrc \
+    .bash_logout \
+    .vimrc \
+    .tmux.conf \
+    fetch.sh
 do
     printf "%s" "copying '$SCRIPT'"
     case $SCRIPT in
-        "fetch.sh")
+        fetch.sh)
             mkdir -p "$HOME/.local/bin/" >/dev/null 2>&1 || continue
             try_run cp "$SCRIPTPATH/base/$SCRIPT" "$HOME/.local/bin/"
             ;;
@@ -144,9 +186,7 @@ do
     esac
 done
 # ---
-if sudo_privilege; then
-    sudo chsh -s "$(command -v bash)" "$USER"
-fi
+sudo chsh -s "$(command -v bash)" "$USER"
 
 
 
diff --git a/podeen_code b/podeen_code
--- a/podeen_code
+++ b/podeen_code
@@ -9,8 +9,17 @@
 ### Functions
 #############
 
-sudo_privilege () {
+sudo_privileges () {
     id -Gn 2>/dev/null | grep -qw "sudo"
+}
+# ---
+ask_user () {
+    printf "%s\n" "$1"
+    read -r -p "wish to proceed anyway? [y/N] " ANS
+    case "$ANS" in
+        y | Y | yes | YES) printf "\n%s\n" "setup resumed" ;;
+        *) printf "\n%s\n" "setup interrupted"; exit 1 ;;
+    esac
 }
 # ---
 try_run () {
@@ -37,8 +46,8 @@ if [ "$(id -u)" -eq 0 ]; then
 fi
 # ---
 if ! command -v code >/dev/null 2>&1; then
-    printf "\n%s"   "═══════ Warning: VSCode not found ══════"
-    printf "\n%s\n" "Install VSCode and run this script again"
+    printf "\n%s"   "═══════ WARNING: VSCode not found ══════"
+    printf "\n%s\n" "install VSCode and run this script again"
     exit 1
 fi
 
@@ -59,19 +68,42 @@ EOF
 
 
 
+### Packages & Sudo
+###################
+
+PACKAGES="git dash bash gnome-keyring pandoc texlive-full \
+python3-full python3-pip black fonts-cascadia-code"
+for PKG in $PACKAGES; do
+    if ! apt-get -s install "$PKG" >/dev/null 2>&1; then
+        PROBLEMS="${PROBLEMS:-} $PKG"
+    fi
+done
+# ---
+if [ -n "$PROBLEMS" ]; then
+    ask_proceed "these packages might cause issues:'$PROBLEMS'"
+fi
+# ---
+if ! sudo_privileges; then
+    ask_proceed "'$USER' does not have sudo privileges"
+fi
+
+
+
+
 ### Path & Dependencies
 #######################
 
 SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )" || exit 1
-if sudo_privilege && command -v apt-get >/dev/null 2>&1; then
-    sudo sh -c '
-        apt-get update &&
-        apt-get upgrade -qq -y --allow-downgrades &&
-        apt-get install -qq -y gnome-keyring fonts-cascadia-code git dash bash pandoc texlive-full python3-full python3-pip black
-        apt-get -qq -y autoremove --purge &&
-        apt-get -qq -y autoclean
-    ' || { printf "\n%s\n" "Package installation failed"; exit 1; }
-fi
+sudo sh -c '
+    apt-get update &&
+    apt-get upgrade -qq -y --allow-downgrades &&
+    apt-get install -qq -y '"$PACKAGES"' || true &&
+    apt-get -qq -y autoremove --purge &&
+    apt-get -qq -y autoclean
+' || {
+    printf "\n%s\n" "packages installation failed"
+    exit 1
+}
 
 
 
@@ -85,7 +117,7 @@ for EXTENSION in $(\code --list-extensions); do
     try_run \code --uninstall-extension "$EXTENSION"
 done
 rm -rf "$HOME/.config/Code/CachedExtensionVSIXs" \
-       "$HOME/.vscode/extensions" 2>/dev/null || true
+      "$HOME/.vscode/extensions" 2>/dev/null || true
 # ---
 printf "\n%s\n" "INSTALLING CODE EXTENSIONS"
 for EXTENSION in \
diff --git a/podeen_plug b/podeen_plug
--- a/podeen_plug
+++ b/podeen_plug
@@ -9,8 +9,17 @@
 ### Functions
 #############
 
-sudo_privilege () {
+sudo_privileges () {
     id -Gn 2>/dev/null | grep -qw "sudo"
+}
+# ---
+ask_user () {
+    printf "%s\n" "$1"
+    read -r -p "wish to proceed anyway? [y/N] " ANS
+    case "$ANS" in
+        y | Y | yes | YES) printf "\n%s\n" "setup resumed" ;;
+        *) printf "\n%s\n" "setup interrupted"; exit 1 ;;
+    esac
 }
 
 
@@ -29,8 +38,8 @@ if [ "$(id -u)" -eq 0 ]; then
 fi
 # ---
 if ! command -v vim >/dev/null 2>&1 || ! \vim --version 2>/dev/null | head -n1 | grep -q 'Vi IMproved 9'; then
-    printf "\n%s"   "═══════ Warning: Vim9 not found ══════"
-    printf "\n%s\n" "Install Vim9 and run this script again"
+    printf "\n%s"   "═══════ WARNING: Vim9 not found ══════"
+    printf "\n%s\n" "install Vim9 and run this script again"
     exit 1
 fi
 
@@ -52,20 +61,42 @@ EOF
 
 
 
+### Packages & Sudo
+###################
+
+PACKAGES="git vim-gtk3 python3-full python3-pip black fonts-cascadia-code"
+for PKG in $PACKAGES; do
+    if ! apt-get -s install "$PKG" >/dev/null 2>&1; then
+        PROBLEMS="${PROBLEMS:-} $PKG"
+    fi
+done
+# ---
+if [ -n "$PROBLEMS" ]; then
+    ask_proceed "these packages might cause issues:'$PROBLEMS'"
+fi
+# ---
+if ! sudo_privileges; then
+    ask_proceed "'$USER' does not have sudo privileges"
+fi
+
+
+
+
 ### Path & Dependencies
 #######################
 
 SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )" || exit 1
-if sudo_privilege && command -v apt-get >/dev/null 2>&1; then
-    sudo sh -c '
-        apt-get update &&
-        apt-get upgrade -qq -y --allow-downgrades &&
-        apt-get purge -qq -y vim-tiny vim || true &&
-        apt-get install -qq -y fonts-cascadia-code git vim-gtk3 python3-full python3-pip black &&
-        apt-get -qq -y autoremove --purge &&
-        apt-get -qq -y autoclean
-    ' || { printf "\n%s\n" "Package installation failed"; exit 1; }
-fi
+sudo sh -c '
+    apt-get update &&
+    apt-get upgrade -qq -y --allow-downgrades &&
+    apt-get purge -qq -y vim-tiny vim || true &&
+    apt-get install -qq -y '"$PACKAGES"' || true &&
+    apt-get -qq -y autoremove --purge &&
+    apt-get -qq -y autoclean
+' || {
+    printf "\n%s\n" "packages installation failed"
+    exit 1
+}
 
 
 
@@ -82,12 +113,10 @@ set -- \
 # ---
 VIM=$HOME/.vim
 START="$VIM/pack/plug/start"
-FOUND=""
-# ---
-mkdir -p "$START" >/dev/null 2>&1 || { printf "\n%s\n" "'$START' failed makedir"; exit 1; }
-if [ ! -d "$VIM/plugin" ] && [ -d "$SCRIPTPATH/plug" ]; then
-    cp -R "$SCRIPTPATH/plug" "$VIM/plugin" >/dev/null 2>&1 || printf "%s\n" "'$VIM/plugin' failed copy"
-fi
+mkdir -p "$START" >/dev/null 2>&1 || {
+    printf "\n%s\n" "makedir '$START' failed"
+    exit 1
+}
 # ---
 for DIR in "$START"/*; do
     [ -e "$DIR" ] && [ -d "$DIR/.git" ] || continue
@@ -96,23 +125,29 @@ for DIR in "$START"/*; do
     \git -C "$DIR" pull --ff-only
     for URL in "$@"; do
         if [ "$ORIGIN" = "$URL" ]; then
-            case " $FOUND " in
+            case " ${FOUND-} " in
                 *" $URL "*) : ;;
-                *) FOUND="$FOUND $URL" ;;
+                *) FOUND="${FOUND:+$FOUND }$URL" ;;
             esac
         fi
     done
 done
 # ---
 for URL in "$@"; do
-    case " $FOUND " in
-        *" $URL "*) : ;;
+    case " ${FOUND-} " in
+        *" $URL "*)
+            { :; }
+            ;;
         *)
             printf "\n%s\n" "CLONING $URL"
             \git -C "$START" clone "$URL"
             ;;
     esac
 done
+# ---
+if [ ! -d "$VIM/plugin" ] && [ -d "$SCRIPTPATH/plug" ]; then
+    cp -R "$SCRIPTPATH/plug" "$VIM/plugin"
+fi
 
 
 
